// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbxxsxwokcanqnwdtcbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhieHhzeHdva2NhbnFud2R0Y2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTYwMDYsImV4cCI6MjA2NTUzMjAwNn0.YkM27j9cU8yD1OM50SnZAbhYJcKiD-IZOZuqQbNr7Fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);